name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: "@insertcoinab"

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Publish
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SSH_KEY: ${{ secrets.GWENNIFER_GITHUB_SSH_KEY }}
        run: |
          PACKAGE_VERSION=${GITHUB_REF/refs\/tags\/v}
          echo $GITHUB_REF
          echo "Releasing version $PACKAGE_VERSION"

          eval "$(ssh-agent -s)"
          ssh-add - <<< "${GITHUB_SSH_KEY}"

          git config --global user.email "gwennifer@insertcoin.se"
          git config --global user.name "Gwennifer"
          git config --global pull.ff only

          git remote remove origin
          git remote add origin "git@github.com:${GITHUB_REPOSITORY}.git"
          git fetch
          git checkout main
          git pull

          yarn publish --new-version $PACKAGE_VERSION --no-git-tag-version

          git add package.json
          git commit -m "Package released => $PACKAGE_VERSION"
          git push -u origin main

      - name: Notify Dependabot
        env:
          GITHUB_PAT: ${{ secrets.GWENNIFER_GITHUB_PAT }}
        run: |
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk '{print $2}' | sed 's/[",]//g')

          curl -s --request POST \
            --url https://api.dependabot.com/release_notifications/private \
            --header "Authorization: Personal $GITHUB_PAT" \
            --header 'content-type: application/json' \
            --data "{\"name\":\"@insertcoinab/gwen-react-components\",\"version\":\"$PACKAGE_VERSION\",\"package-manager\":\"npm_and_yarn\"}"
