name: Test
on: pull_request_target

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - uses: actions/setup-node@v3.5.0

      - name: Install
        run: yarn install

      - name: Test Types
        run: yarn test:types

      - name: Test Lint
        run: yarn test:lint

      - name: Build
        run: yarn build

      - name: Build Docz
        run: yarn docz:build
